### ISSUE TITLE
Put project on PyPI and create Github releases

### ISSUE THREAD

**Issue by SpotlightKid** [jisaacstone/sfzlint#7]
It would be nice if this project was also listed on PyPI.

* Create an account on PyPI.
* Build source and wheel package: `python setup.py bdist_wheel sdist --format=gztar`
* Upload the packages: `twine upload --skip-existing dist/*`

Also, if project releases were created on Github (not just tagged) it would be easier for interested parties, e.g. distribution package creators, to get notified of new releases (because there doesn't seem to be an option on Github to get notified only about new tags of a project).

**Comment by jisaacstone** [comment]
Done and Done :)
