### ISSUE TITLE
1/0

### ISSUE THREAD

**Issue by ariutti** [jisaacstone/sfzlint#9]
Hi,
thank you for your job and this useful tool. I would like to use it to list all the opcodes inside some SFZ files I have.

Everytime I try to use it from the command line like this:

`sfzlist --path "/home/nicola/Musica/Samples/Sonatina Symphonic Orchestra/Brass - Bass Trombone Solo.sfz"`

I get this error

```
Traceback (most recent call last):
  File "/usr/local/bin/sfzlist", line 11, in <module>
    load_entry_point('sfzlint==0.1.4', 'console_scripts', 'sfzlist')()
  File "/usr/local/lib/python3.6/dist-packages/sfzlint-0.1.4-py3.6.egg/sfzlint/cli.py", line 90, in sfzlist
    1/0
ZeroDivisionError: division by zero
```

So I've examined the `sfzlint/cli.py` at [line 90](https://github.com/jisaacstone/sfzlint/blob/3c304c021d0c3b55e310adb99333fd0a3186a70a/sfzlint/cli.py#L90) and I found something strange which I commented out before installing the tool again with the command `sudo python3 setup.py install`.

Now I don't see any error anymore but the command:

`sfzlist --path "/home/nicola/Musica/Samples/Sonatina Symphonic Orchestra/Brass - Bass Trombone Solo.sfz"`

returns nothing.

Why?
What Am I doing wrong?

Thank you so much for your support!

**Comment by jisaacstone** [comment]
oops, the 1/0 was for debugging and should not have been left in. Apologies

somehow I wrote sfzlist only to work on directories, not individual files. Not sure why I did that. Have pushed tag v0.1.5 , should support files and directories for sfzlist.
